services:
  - type: web
    name: crop-disease-api
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install fastapi uvicorn[standard] python-multipart requests
    startCommand: uvicorn simple_test:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: API_KEY
        value: u12lFbhGXOPacNJgi4pqK2scNsm34OryIiw99IIPJLKzjgntD5
      - key: DEEPSEEK_API_KEY
        value: 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
